[package]
name = "gc-logbook"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rusqlite = { version = "0.28.0", features = ["chrono"] }
