[package]
name = "gc-logbook"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_sync_db_pools = { version = "0.1.0-rc.2", features = ["rusqlite"] }
